openapi: 3.2.0
info:
  title: Public API Reference Product / BOM Placements API
  description: 'The retraced API comprises all publicly enabled options to make

    machine-to-machine changes in the retraced platform.'
  version: 2.938.1
servers: []
tags:
- name: Product / BOM Placements
paths:
  /api/v2/bom-placements/:
    post:
      tags:
      - Product / BOM Placements
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: string
                  minLength: 1
                  maxLength: 255
              required:
              - value
      responses:
        '201':
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    type: object
                    properties:
                      success:
                        default: true
                        type: boolean
                      pagination:
                        type: object
                        properties:
                          page:
                            default: 1
                            type: number
                          limit:
                            default: 10
                            type: number
                          total:
                            default: 0
                            type: number
                          totalPages:
                            default: 0
                            type: number
                        required:
                        - page
                        - limit
                        - total
                        - totalPages
                        additionalProperties: false
                    required:
                    - success
                    additionalProperties: false
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        minLength: 1
                      value:
                        type: string
                        minLength: 1
                      forCompanyId:
                        type: string
                        minLength: 1
                      createdAt:
                        anyOf:
                        - type: string
                        - type: string
                          format: date-time
                      createdByUserId:
                        anyOf:
                        - type: string
                        - type: 'null'
                      createdByCompanyId:
                        anyOf:
                        - type: string
                        - type: 'null'
                      updatedAt:
                        anyOf:
                        - type: string
                        - type: string
                          format: date-time
                      updatedByUserId:
                        anyOf:
                        - type: string
                        - type: 'null'
                      updatedByCompanyId:
                        anyOf:
                        - type: string
                        - type: 'null'
                    required:
                    - id
                    - value
                    - forCompanyId
                    - createdAt
                    - updatedAt
                    additionalProperties: false
                required:
                - metadata
                - data
                additionalProperties: false
        '400':
          description: No content
      summary: Create api bom placements
      x-summary-source: derived
      operationId: postApiV2BomPlacements
      x-operation-id-source: derived
    get:
      tags:
      - Product / BOM Placements
      parameters:
      - schema:
          default: 1
          type: integer
          minimum: 1
          maximum: 9007199254740991
        in: query
        name: page
        required: false
      - schema:
          default: 20
          type: integer
          minimum: 1
          maximum: 100
        in: query
        name: limit
        required: false
      - schema:
          default: desc
          type: string
          enum:
          - asc
          - desc
          - ASC
          - DESC
        in: query
        name: order
        required: false
      - schema:
          default: createdAt
          type: string
          enum:
          - createdAt
          - updatedAt
          - value
        in: query
        name: sort
        required: false
      - schema:
          type: string
        in: query
        name: ids
        required: false
      - schema:
          type: string
        in: query
        name: value
        required: false
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    type: object
                    properties:
                      success:
                        default: true
                        type: boolean
                      pagination:
                        type: object
                        properties:
                          page:
                            default: 1
                            type: number
                          limit:
                            default: 10
                            type: number
                          total:
                            default: 0
                            type: number
                          totalPages:
                            default: 0
                            type: number
                        required:
                        - page
                        - limit
                        - total
                        - totalPages
                        additionalProperties: false
                    required:
                    - success
                    additionalProperties: false
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          minLength: 1
                        value:
                          type: string
                          minLength: 1
                        forCompanyId:
                          type: string
                          minLength: 1
                        createdAt:
                          anyOf:
                          - type: string
                          - type: string
                            format: date-time
                        createdByUserId:
                          anyOf:
                          - type: string
                          - type: 'null'
                        createdByCompanyId:
                          anyOf:
                          - type: string
                          - type: 'null'
                        updatedAt:
                          anyOf:
                          - type: string
                          - type: string
                            format: date-time
                        updatedByUserId:
                          anyOf:
                          - type: string
                          - type: 'null'
                        updatedByCompanyId:
                          anyOf:
                          - type: string
                          - type: 'null'
                      required:
                      - id
                      - value
                      - forCompanyId
                      - createdAt
                      - updatedAt
                      additionalProperties: false
                required:
                - metadata
                - data
                additionalProperties: false
      summary: Get api bom placements
      x-summary-source: derived
      operationId: getApiV2BomPlacements
      x-operation-id-source: derived
  /api/v2/bom-placements/{id}:
    get:
      tags:
      - Product / BOM Placements
      parameters:
      - schema:
          type: string
          minLength: 1
        in: path
        name: id
        required: true
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    type: object
                    properties:
                      success:
                        default: true
                        type: boolean
                      pagination:
                        type: object
                        properties:
                          page:
                            default: 1
                            type: number
                          limit:
                            default: 10
                            type: number
                          total:
                            default: 0
                            type: number
                          totalPages:
                            default: 0
                            type: number
                        required:
                        - page
                        - limit
                        - total
                        - totalPages
                        additionalProperties: false
                    required:
                    - success
                    additionalProperties: false
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        minLength: 1
                      value:
                        type: string
                        minLength: 1
                      forCompanyId:
                        type: string
                        minLength: 1
                      createdAt:
                        anyOf:
                        - type: string
                        - type: string
                          format: date-time
                      createdByUserId:
                        anyOf:
                        - type: string
                        - type: 'null'
                      createdByCompanyId:
                        anyOf:
                        - type: string
                        - type: 'null'
                      updatedAt:
                        anyOf:
                        - type: string
                        - type: string
                          format: date-time
                      updatedByUserId:
                        anyOf:
                        - type: string
                        - type: 'null'
                      updatedByCompanyId:
                        anyOf:
                        - type: string
                        - type: 'null'
                    required:
                    - id
                    - value
                    - forCompanyId
                    - createdAt
                    - updatedAt
                    additionalProperties: false
                required:
                - metadata
                - data
                additionalProperties: false
      summary: Get api bom placements by id
      x-summary-source: derived
      operationId: getApiV2BomPlacementsById
      x-operation-id-source: derived
