openapi: 3.2.0
info:
  title: Public API Reference Order Hub / Attachment Templates API
  description: 'The retraced API comprises all publicly enabled options to make

    machine-to-machine changes in the retraced platform.'
  version: 2.938.1
servers: []
tags:
- name: Order Hub / Attachment Templates
paths:
  /api/v2/attachment-templates/:
    get:
      tags:
      - Order Hub / Attachment Templates
      parameters:
      - schema:
          default: 0
          type: integer
          minimum: 0
          maximum: 9007199254740991
        in: query
        name: page
        required: false
      - schema:
          default: 20
          type: integer
          minimum: 1
          maximum: 100
        in: query
        name: count
        required: false
      - schema:
          type: string
        in: query
        name: name
        required: false
      - schema:
          type: string
          enum:
          - PRODUCT_BACKWARD
        in: query
        name: tracingType
        required: false
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      count:
                        type: number
                      page:
                        type: number
                      totalCount:
                        type: number
                      pageSize:
                        type: number
                    required:
                    - count
                    - page
                    - totalCount
                    - pageSize
                    additionalProperties: false
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        description:
                          anyOf:
                          - type: string
                          - type: 'null'
                        companyId:
                          type: string
                        isGlobal:
                          type: boolean
                        isArchived:
                          type: boolean
                        isActive:
                          type: boolean
                        isPreference:
                          type: boolean
                        tracingType:
                          type: string
                        createdAt:
                          type: string
                          format: date-time
                        updatedAt:
                          type: string
                          format: date-time
                      required:
                      - id
                      - name
                      - description
                      - companyId
                      - isGlobal
                      - isArchived
                      - isActive
                      - isPreference
                      - tracingType
                      - createdAt
                      - updatedAt
                      additionalProperties: false
                required:
                - meta
                - data
                additionalProperties: false
        '401':
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    type: object
                    properties:
                      success:
                        default: false
                        type: boolean
                    required:
                    - success
                    additionalProperties: false
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  expected:
                    type: boolean
                required:
                - statusCode
                - code
                - message
                additionalProperties: false
      summary: Get api attachment templates
      x-summary-source: derived
      operationId: getApiV2AttachmentTemplates
      x-operation-id-source: derived
