openapi: 3.0.3
info:
  title: Public API Reference Certificates Order Hub / Attachment Templates API
  description: 'The retraced API comprises all publicly enabled options to make

    machine-to-machine changes in the retraced platform. The retraced dashboard uses the

    same endpoints, but also in addition more. If you wish to use the API of the dashboard,

    it is possible but not versioned cleanly like the public API.


    ## Authentication


    The authentication procedure is passwordless and uses an API key in the header. To get

    an API key log into the Retraced Platform and navigate to **Developers HQ > API Keys**

    then click **Create**. Be sure to copy the key somewhere safe, as you won''t be able to

    view it again. If you don''t see Developers HQ in the sidebar contact your Customer

    Success Manager to enable this for you. You can now set the key directly in request

    headers. To authenticate using an API key, set the header key `companyapikey` to the

    value of your API key.


    ## Getting Started


    Retraced has 2 environments against which you can send your requests and receive the

    expected response: staging (for development and testing) and production. Your API key

    is scoped for both environments. The staging Base URL is

    https://publicapi.staging.retraced.com. Staging copies production data once daily, and

    all changes made on staging will be deleted.


    Find detailed guides on how to use the endpoints and how we recommend building an

    integration given your use case in our

    [guides](https://publicapi.retraced.com/api/v2/guides). A history of public API

    changes is available in the

    [release notes](https://publicapi.retraced.com/api/v2/release-notes).'
  version: 2.938.1
servers: []
tags:
- name: Order Hub / Attachment Templates
paths:
  /api/v2/attachment-templates/:
    get:
      tags:
      - Order Hub / Attachment Templates
      parameters:
      - schema:
          default: 0
          type: integer
          minimum: 0
          maximum: 9007199254740991
        in: query
        name: page
        required: false
      - schema:
          default: 20
          type: integer
          minimum: 1
          maximum: 100
        in: query
        name: count
        required: false
      - schema:
          type: string
        in: query
        name: name
        required: false
      - schema:
          type: string
          enum:
          - PRODUCT_BACKWARD
        in: query
        name: tracingType
        required: false
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      count:
                        type: number
                      page:
                        type: number
                      totalCount:
                        type: number
                      pageSize:
                        type: number
                    required:
                    - count
                    - page
                    - totalCount
                    - pageSize
                    additionalProperties: false
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        description:
                          anyOf:
                          - type: string
                          - type: 'null'
                        companyId:
                          type: string
                        isGlobal:
                          type: boolean
                        isArchived:
                          type: boolean
                        isActive:
                          type: boolean
                        isPreference:
                          type: boolean
                        tracingType:
                          type: string
                        createdAt:
                          type: string
                          format: date-time
                        updatedAt:
                          type: string
                          format: date-time
                      required:
                      - id
                      - name
                      - description
                      - companyId
                      - isGlobal
                      - isArchived
                      - isActive
                      - isPreference
                      - tracingType
                      - createdAt
                      - updatedAt
                      additionalProperties: false
                required:
                - meta
                - data
                additionalProperties: false
        '401':
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    type: object
                    properties:
                      success:
                        default: false
                        type: boolean
                    required:
                    - success
                    additionalProperties: false
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  expected:
                    type: boolean
                required:
                - statusCode
                - code
                - message
                additionalProperties: false
