openapi: 3.2.0
info:
  title: Public API Reference Guides API
  description: 'The retraced API comprises all publicly enabled options to make

    machine-to-machine changes in the retraced platform.'
  version: 2.938.1
servers: []
tags:
- name: Guides
paths:
  /api/v2/guides:
    get:
      responses:
        '200':
          description: Default Response
      tags:
      - Guides
      summary: Get api guides
      x-summary-source: derived
      operationId: getApiV2Guides
      x-operation-id-source: derived
  /api/v2/guides/products:
    get:
      responses:
        '200':
          description: Default Response
      tags:
      - Guides
      summary: Get api guides products
      x-summary-source: derived
      operationId: getApiV2GuidesProducts
      x-operation-id-source: derived
  /api/v2/guides/lca-provider:
    get:
      responses:
        '200':
          description: Default Response
      tags:
      - Guides
      summary: Get api guides lca provider
      x-summary-source: derived
      operationId: getApiV2GuidesLcaProvider
      x-operation-id-source: derived
  /api/v2/guides/dpp-label-provider:
    get:
      responses:
        '200':
          description: Default Response
      tags:
      - Guides
      summary: Get api guides dpp label provider
      x-summary-source: derived
      operationId: getApiV2GuidesDppLabelProvider
      x-operation-id-source: derived
  /api/v2/guides/bom:
    get:
      responses:
        '200':
          description: Default Response
      tags:
      - Guides
      summary: Get api guides bom
      x-summary-source: derived
      operationId: getApiV2GuidesBom
      x-operation-id-source: derived
  /api/v2/guides/materials:
    get:
      responses:
        '200':
          description: Default Response
      tags:
      - Guides
      summary: Get api guides materials
      x-summary-source: derived
      operationId: getApiV2GuidesMaterials
      x-operation-id-source: derived
  /api/v2/guides/file-upload:
    get:
      responses:
        '200':
          description: Default Response
      tags:
      - Guides
      summary: Get api guides file upload
      x-summary-source: derived
      operationId: getApiV2GuidesFileUpload
      x-operation-id-source: derived
  /api/v2/guides/order-hub:
    get:
      responses:
        '200':
          description: Default Response
      tags:
      - Guides
      summary: Get api guides order hub
      x-summary-source: derived
      operationId: getApiV2GuidesOrderHub
      x-operation-id-source: derived
