openapi: 3.2.0
info:
  title: Public API Reference Certificates API
  description: 'The retraced API comprises all publicly enabled options to make

    machine-to-machine changes in the retraced platform.'
  version: 2.938.1
servers: []
tags:
- name: Certificates
paths:
  /api/v2/certificates/:
    get:
      tags:
      - Certificates
      description: List certificates
      parameters:
      - schema:
          type: integer
          minimum: 1
          maximum: 500
        in: query
        name: limit
        required: false
      - schema:
          type: integer
          minimum: 1
          maximum: 9007199254740991
        in: query
        name: page
        required: false
      - schema:
          default: desc
          type: string
          enum:
          - asc
          - desc
          - ASC
          - DESC
        in: query
        name: order
        required: false
      - schema:
          default: name
          type: string
          enum:
          - name
          - companyName
          - status
          - updatedAt
          - expirationDate
          - type
          - documentNumber
          - licenseNumber
          - issueDate
          - issuedBy
        in: query
        name: sort
        required: false
      - schema:
          type: string
        in: query
        name: status
        required: false
      - schema:
          type: string
        in: query
        name: type
        required: false
      - schema:
          type: string
        in: query
        name: companyId
        required: false
      - schema:
          type: string
        in: query
        name: standardId
        required: false
      - schema:
          type: string
        in: query
        name: filter
        required: false
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    type: object
                    properties:
                      success:
                        default: true
                        type: boolean
                      pagination:
                        type: object
                        properties:
                          page:
                            default: 1
                            type: number
                          limit:
                            default: 10
                            type: number
                          total:
                            default: 0
                            type: number
                          totalPages:
                            default: 0
                            type: number
                        required:
                        - page
                        - limit
                        - total
                        - totalPages
                        additionalProperties: false
                    required:
                    - success
                    additionalProperties: false
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          minLength: 1
                        name:
                          type: string
                          minLength: 1
                        type:
                          type: string
                          enum:
                          - MEMBERSHIP
                          - PRODUCT
                          - TRANSACTION
                          - COMPANY
                          - SCOPE
                        companyId:
                          type: string
                          minLength: 1
                        companyName:
                          anyOf:
                          - type: string
                            minLength: 1
                          - type: 'null'
                        companyOfficialName:
                          anyOf:
                          - type: string
                            minLength: 1
                          - type: 'null'
                        documentNumber:
                          anyOf:
                          - type: string
                            minLength: 1
                          - type: 'null'
                        licenseNumber:
                          anyOf:
                          - type: string
                            minLength: 1
                          - type: 'null'
                        issueDate:
                          anyOf:
                          - anyOf:
                            - type: string
                            - type: string
                              format: date-time
                          - type: 'null'
                        issuedBy:
                          anyOf:
                          - type: string
                          - type: 'null'
                        expirationDate:
                          anyOf:
                          - anyOf:
                            - type: string
                            - type: string
                              format: date-time
                          - type: 'null'
                        explanation:
                          anyOf:
                          - type: string
                          - type: 'null'
                        status:
                          type: string
                          enum:
                          - DRAFT
                          - REQUESTED
                          - APPROVED
                          - REJECTED
                          - ACKNOWLEDGED
                          - NOT_VERIFIABLE
                        fileUrl:
                          anyOf:
                          - type: string
                            minLength: 1
                            maxLength: 255
                          - type: 'null'
                        fileContentType:
                          anyOf:
                          - type: string
                            minLength: 1
                          - type: 'null'
                      required:
                      - id
                      - name
                      - type
                      - companyId
                      - status
                      additionalProperties: false
                required:
                - metadata
                - data
                additionalProperties: false
        '401':
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    type: object
                    properties:
                      success:
                        default: false
                        type: boolean
                    required:
                    - success
                    additionalProperties: false
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  expected:
                    type: boolean
                required:
                - statusCode
                - code
                - message
                additionalProperties: false
      summary: Get api certificates
      x-summary-source: derived
      operationId: getApiV2Certificates
      x-operation-id-source: derived
  /api/v2/certificates/{id}:
    get:
      tags:
      - Certificates
      description: Get certificate by ID
      parameters:
      - schema:
          type: string
          minLength: 1
        in: path
        name: id
        required: true
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    type: object
                    properties:
                      success:
                        default: true
                        type: boolean
                    required:
                    - success
                    additionalProperties: false
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        minLength: 1
                      name:
                        type: string
                        minLength: 1
                      type:
                        type: string
                        enum:
                        - MEMBERSHIP
                        - PRODUCT
                        - TRANSACTION
                        - COMPANY
                        - SCOPE
                      companyId:
                        type: string
                        minLength: 1
                      companyName:
                        anyOf:
                        - type: string
                          minLength: 1
                        - type: 'null'
                      companyOfficialName:
                        anyOf:
                        - type: string
                          minLength: 1
                        - type: 'null'
                      documentNumber:
                        anyOf:
                        - type: string
                          minLength: 1
                        - type: 'null'
                      licenseNumber:
                        anyOf:
                        - type: string
                          minLength: 1
                        - type: 'null'
                      issueDate:
                        anyOf:
                        - anyOf:
                          - type: string
                          - type: string
                            format: date-time
                        - type: 'null'
                      issuedBy:
                        anyOf:
                        - type: string
                        - type: 'null'
                      expirationDate:
                        anyOf:
                        - anyOf:
                          - type: string
                          - type: string
                            format: date-time
                        - type: 'null'
                      explanation:
                        anyOf:
                        - type: string
                        - type: 'null'
                      status:
                        type: string
                        enum:
                        - DRAFT
                        - REQUESTED
                        - APPROVED
                        - REJECTED
                        - ACKNOWLEDGED
                        - NOT_VERIFIABLE
                      fileUrl:
                        anyOf:
                        - type: string
                          minLength: 1
                          maxLength: 255
                        - type: 'null'
                      fileContentType:
                        anyOf:
                        - type: string
                          minLength: 1
                        - type: 'null'
                    required:
                    - id
                    - name
                    - type
                    - companyId
                    - status
                    additionalProperties: false
                required:
                - metadata
                - data
                additionalProperties: false
        '403':
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    type: object
                    properties:
                      success:
                        default: false
                        type: boolean
                    required:
                    - success
                    additionalProperties: false
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  expected:
                    type: boolean
                required:
                - statusCode
                - code
                - message
                additionalProperties: false
        '404':
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    type: object
                    properties:
                      success:
                        default: false
                        type: boolean
                    required:
                    - success
                    additionalProperties: false
                  statusCode:
                    type: number
                  code:
                    type: string
                  error:
                    type: string
                  message:
                    type: string
                  expected:
                    type: boolean
                required:
                - statusCode
                - code
                - message
                additionalProperties: false
      summary: Get api certificates by id
      x-summary-source: derived
      operationId: getApiV2CertificatesById
      x-operation-id-source: derived
