openapi: 3.2.0
info:
  title: Public API Reference Files API
  description: 'The retraced API comprises all publicly enabled options to make

    machine-to-machine changes in the retraced platform.'
  version: 2.938.1
servers: []
tags:
- name: Files
paths:
  /api/v2/files/:
    post:
      tags:
      - Files
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                  minLength: 1
                fileSize:
                  type: number
                  minimum: 1
                  maximum: 1073741824
                fileType:
                  type: string
                  enum:
                  - image/jpeg
                  - image/png
                  - image/gif
                  - image/webp
                  - image/bmp
                  - image/tiff
                  - image/heic
                  - video/mp4
                  - video/webm
                  - video/quicktime
                  - video/x-msvideo
                  - video/x-matroska
                  - application/pdf
                  - text/rtf
                  - application/msword
                  - application/vnd.openxmlformats-officedocument.wordprocessingml.document
                  - application/vnd.ms-excel
                  - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                  - text/csv
                  - application/vnd.ms-powerpoint
                  - application/vnd.openxmlformats-officedocument.presentationml.presentation
              required:
              - filename
              - fileSize
              - fileType
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  metadata:
                    type: object
                    properties:
                      success:
                        default: true
                        type: boolean
                    required:
                    - success
                    additionalProperties: false
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        minLength: 1
                      bucketName:
                        type: string
                        enum:
                        - public
                        - private
                        - incoming
                      url:
                        type: string
                        minLength: 1
                      name:
                        type: string
                        minLength: 1
                      fileType:
                        anyOf:
                        - type: string
                          enum:
                          - IMAGE
                          - VIDEO
                          - DOCUMENT
                        - type: 'null'
                      documentText:
                        anyOf:
                        - type: string
                        - type: 'null'
                      contentType:
                        anyOf:
                        - type: string
                          enum:
                          - application/msword
                          - application/vnd.openxmlformats-officedocument.wordprocessingml.document
                          - application/octet-stream
                          - application/pdf
                          - text/rtf
                          - application/vnd.ms-powerpoint
                          - application/vnd.openxmlformats-officedocument.presentationml.presentation
                          - application/vnd.ms-excel
                          - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                          - application/kswps
                          - application/zip
                          - binary/octet-stream
                          - IMAGE
                          - image/bmp
                          - image/gif
                          - image/heic
                          - image/jpeg
                          - image/png
                          - image/svg+xml
                          - image/tiff
                          - image/webp
                          - text/csv
                          - video/mp4
                          - video/webm
                          - video/quicktime
                          - video/x-msvideo
                          - video/x-matroska
                        - type: 'null'
                      contentMd5Hash:
                        anyOf:
                        - type: string
                        - type: 'null'
                      fileHash:
                        anyOf:
                        - type: string
                        - type: 'null'
                      fileSize:
                        anyOf:
                        - type: number
                        - type: 'null'
                      isMigrated:
                        anyOf:
                        - type: integer
                          minimum: 0
                          maximum: 1
                        - type: 'null'
                      isPrivate:
                        anyOf:
                        - type: integer
                          minimum: 0
                          maximum: 1
                        - type: 'null'
                      uploadUrl:
                        anyOf:
                        - type: string
                        - type: 'null'
                      originalUrl:
                        anyOf:
                        - type: string
                        - type: 'null'
                      previewUrl:
                        anyOf:
                        - type: string
                        - type: 'null'
                      createdAt:
                        anyOf:
                        - type: string
                          format: date-time
                        - type: 'null'
                      createdBy:
                        anyOf:
                        - type: string
                        - type: 'null'
                      createdByCompanyId:
                        anyOf:
                        - type: string
                        - type: 'null'
                      createdByApiKeyId:
                        anyOf:
                        - type: string
                        - type: 'null'
                      createdByApiKeyLabel:
                        anyOf:
                        - type: string
                        - type: 'null'
                      createdByImpersonateId:
                        anyOf:
                        - type: string
                        - type: 'null'
                      createdByImpersonateName:
                        anyOf:
                        - type: string
                        - type: 'null'
                      createdByUserId:
                        anyOf:
                        - type: string
                        - type: 'null'
                      updatedAt:
                        anyOf:
                        - type: string
                          format: date-time
                        - type: 'null'
                      updatedByApiKeyId:
                        anyOf:
                        - type: string
                        - type: 'null'
                      updatedByApiKeyLabel:
                        anyOf:
                        - type: string
                        - type: 'null'
                      updatedByCompanyId:
                        anyOf:
                        - type: string
                        - type: 'null'
                      updatedByCompanyName:
                        anyOf:
                        - type: string
                        - type: 'null'
                      updatedByImpersonateId:
                        anyOf:
                        - type: string
                        - type: 'null'
                      updatedByImpersonateName:
                        anyOf:
                        - type: string
                        - type: 'null'
                      updatedByUserId:
                        anyOf:
                        - type: string
                        - type: 'null'
                      updatedByUserName:
                        anyOf:
                        - type: string
                        - type: 'null'
                      normalizeAttemptedAt:
                        anyOf:
                        - type: string
                          format: date-time
                        - type: 'null'
                    required:
                    - id
                    - bucketName
                    - url
                    - name
                    - fileType
                    - contentType
                    - fileHash
                    - fileSize
                    - isMigrated
                    - isPrivate
                    - createdAt
                    - createdBy
                    - createdByCompanyId
                    - createdByApiKeyId
                    - createdByApiKeyLabel
                    - createdByImpersonateId
                    - createdByImpersonateName
                    - createdByUserId
                    - updatedAt
                    - updatedByApiKeyId
                    - updatedByApiKeyLabel
                    - updatedByCompanyId
                    - updatedByCompanyName
                    - updatedByImpersonateId
                    - updatedByImpersonateName
                    - updatedByUserId
                    - updatedByUserName
                    additionalProperties: false
                required:
                - metadata
                - data
                additionalProperties: false
      summary: Create api files
      x-summary-source: derived
      operationId: postApiV2Files
      x-operation-id-source: derived
