openapi: 3.2.0
info:
  title: Public API Reference Release Notes API
  description: 'The retraced API comprises all publicly enabled options to make

    machine-to-machine changes in the retraced platform.'
  version: 2.938.1
servers: []
tags:
- name: Release Notes
paths:
  /api/v2/release-notes:
    get:
      responses:
        '200':
          description: Default Response
      tags:
      - Release Notes
      summary: Get api release notes
      x-summary-source: derived
      operationId: getApiV2ReleaseNotes
      x-operation-id-source: derived
